<?php
/**
 * Route registry — one entry per indexable URL.
 * Default migration action for every existing URL is KEEP URL UNCHANGED
 * (see docs/url-inventory.md). Title/description fixes applied here are
 * documented in docs/audit-findings.md — nothing else was changed from
 * what's live today.
 *
 * template: which templates/{template}.php renders this route
 * slug: content/pages/{slug}.php holds the page body
 */
return [
    '/' => [
        'slug' => '__home__',
        'template' => 'home',
        'title' => 'Expert Artificial Turf Cleaning in DFW Texas | Clean Green Turf',
        'description' => 'Clean Green Turf provides artificial turf cleaning, installation, and repair across the Dallas Fort Worth Metroplex. We restore, install, and fix turf so your outdoor space always looks its best.',
        'schema_types' => ['WebSite'],
    ],
    '/about' => [
        'slug' => 'about',
        'template' => 'page',
        'title' => 'About Clean Green Turf | Artificial Turf Cleaning in DFW, TX',
        'description' => 'Clean Green Turf specializes in artificial turf cleaning, installation, and repair. Serving the Dallas Fort Worth Metroplex, we restore, install, and fix turf for a great-looking outdoor space year-round.',
        'schema_types' => ['WebPage'],
    ],
    '/addison-tx-turf-cleaning' => [
        'slug' => 'addison-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'Addison TX Turf Cleaning — Residential and Commercial, Pet-Safe Every Time | Clean Green Turf',
        'description' => 'Turf cleaning in Addison, TX for residential and commercial properties. Pet odor extraction, power brushing, infill replenishment. DFW-local and pet-safe. Free quote: (469) 796-0034.',
        'schema_types' => ['WebPage'],
    ],
    '/allen-tx-turf-cleaning' => [
        'slug' => 'allen-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'Allen-TX-turf-cleaning | Clean Green Turf',
        'description' => 'Elevate your Allen, TX artificial turf with Clean Green Turf’s efficient, eco-friendly cleaning. Fast service, fair pricing, and odor elimination for a pristine, safe lawn—quality guaranteed!',
        'schema_types' => ['WebPage'],
    ],
    '/antioch-ca-turf-cleaning' => [
        'slug' => 'antioch-ca-turf-cleaning',
        'template' => 'page',
        'title' => 'Antioch-CA-turf-cleaning | Clean Green Turf',
        'description' => 'Transform your Antioch, CA landscape with Clean Green Turf\'s cutting-edge, eco-friendly artificial turf cleaning services. Enjoy sustainable, spotless, and vibrant turf with our advanced, meticulous solutions.',
        'schema_types' => ['WebPage'],
    ],
    '/austin-tx' => [
        'slug' => 'austin-tx',
        'template' => 'page',
        'title' => 'Austin, TX Artificial Turf Cleaning | Clean Green Turf',
        'description' => 'Professional artificial turf cleaning in Austin, TX. Pet odor extraction, power brushing, infill replenishment. Free quote: (469) 796-0034.',
        'schema_types' => ['WebPage'],
    ],
    '/berkeley-ca-turf-cleaning' => [
        'slug' => 'berkeley-ca-turf-cleaning',
        'template' => 'page',
        'title' => 'Berkeley-CA-turf-cleaning | Clean Green Turf',
        'description' => 'Experience efficient, eco-friendly artificial turf cleaning with Clean Green Turf in Berkeley, CA. Our quick, thorough, and sustainable methods ensure vibrant, hygienic turf that enhances your landscape while protecting the planet.',
        'schema_types' => ['WebPage'],
    ],
    '/brentwood-ca-turf-cleaning' => [
        'slug' => 'brentwood-ca-turf-cleaning',
        'template' => 'page',
        'title' => 'Brentwood-CA-turf-cleaning | Clean Green Turf',
        'description' => 'Discover fast, eco-friendly, and professional artificial turf cleaning with Clean Green Turf in Brentwood, CA. Our reliable, top-notch service ensures a pristine turf while supporting sustainability. Refresh your artificial turf today!',
        'schema_types' => ['WebPage'],
    ],
    '/ca-turf-cleaning-service-areas' => [
        'slug' => 'ca-turf-cleaning-service-areas',
        'template' => 'page',
        'title' => 'CA Artificial Turf Cleaning Service Areas | Clean Green Turf',
        'description' => 'Discover Clean Green Turf\'s artificial turf cleaning services for residential areas, commercial properties, sports facilities, schools, golf courses, parks, pet care facilities, and event venues. Ensure pristine, safe, and sustainable outdoor spaces with our expert care.',
        'schema_types' => ['WebPage'],
    ],
    '/celina-tx-turf-cleaning' => [
        'slug' => 'celina-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'Celina-TX-turf-cleaning | Clean Green Turf',
        'description' => 'Unleash a fresher, greener artificial lawn with Clean Green Turf’s swift, eco-conscious cleaning services. We banish odors and restore vibrancy with meticulous care and fair pricing—sustainability meets excellence!',
        'schema_types' => ['WebPage'],
    ],
    '/clayton-ca-turf-cleaning' => [
        'slug' => 'clayton-ca-turf-cleaning',
        'template' => 'page',
        'title' => 'Clayton-CA-turf-cleaning | Clean Green Turf',
        'description' => 'Transform your Clayton, CA turf with Clean Green Turf’s snappy, eco-friendly cleaning magic! Our thorough, planet-loving solutions blast dirt away, boosting your turf’s life, safety, and wow-factor in no time!',
        'schema_types' => ['WebPage'],
    ],
    '/concord-ca-turf-cleaning' => [
        'slug' => 'concord-ca-turf-cleaning',
        'template' => 'page',
        'title' => 'Concord-CA-turf-cleaning | Clean Green Turf',
        'description' => 'Revitalize your Concord, CA artificial turf with Clean Green Turf’s efficient, eco-friendly cleaning services. Our expert team delivers quick, non-toxic solutions for lush, safe, and long-lasting turf that shines—naturally!',
        'schema_types' => ['WebPage'],
    ],
    '/contact' => [
        'slug' => 'contact',
        'template' => 'page',
        'title' => 'Contact Clean Green Turf | Artificial Turf Cleaning in DFW, TX',
        'description' => 'Contact Clean Green Turf for professional artificial turf cleaning, installation, and repair in the Dallas Fort Worth Metroplex. Reach out to us today!',
        'schema_types' => ['WebPage'],
    ],
    '/dallas-tx-turf-cleaning' => [
        'slug' => 'dallas-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'Artificial Turf Cleaning in Dallas, TX | Clean Green Turf',
        'description' => 'Professional artificial turf cleaning in Dallas, TX. We fully extract pet odors, deep clean, and restore your turf. Pet-safe, family-safe, and built for DFW summers. Free quote: (469) 796-0034.',
        'schema_types' => ['WebPage'],
    ],
    '/danville-ca-turf-cleaning' => [
        'slug' => 'danville-ca-turf-cleaning',
        'template' => 'page',
        'title' => 'Danville-CA-turf-cleaning | Clean Green Turf',
        'description' => 'Unleash the brilliance of your Danville, CA artificial turf with Clean Green Turf’s fast, thorough cleaning services. Our expert team blends speed and precision to revitalize your turf, banishing dirt, odors, and bacteria for a vibrant, safe oasis!',
        'schema_types' => ['WebPage'],
    ],
    '/dfw-turf-cleaning-request-ga' => [
        'slug' => 'dfw-turf-cleaning-request-ga',
        'template' => 'page',
        'title' => 'DFW Artificial Turf Cleaning — Request Your Free Quote | Clean Green Turf',
        'description' => 'Request your free DFW artificial turf cleaning quote. Fast response, pet-safe process, serving the entire Dallas Fort Worth metroplex.',
        'schema_types' => ['WebPage'],
    ],
    '/dfw-turf-cleaning-request-success' => [
        'slug' => 'dfw-turf-cleaning-request-success',
        'template' => 'page',
        'title' => 'Expert Artificial Turf Cleaning in Texas | Clean Green Turf',
        'description' => 'Thank you for filling out our online form. We will be back to you shortly with your turf cleaning quote',
        'schema_types' => ['WebPage'],
    ],
    '/discovery-bay-ca-turf-cleaning' => [
        'slug' => 'discovery-bay-ca-turf-cleaning',
        'template' => 'page',
        'title' => 'Discovery Bay-CA-turf-cleaning | Clean Green Turf',
        'description' => 'Keep your artificial lawn pristine in Discovery Bay with Clean Green Turf’s essential maintenance tips and expert cleaning services. Boost lifespan, beauty, and safety with regular care—your turf’s longevity starts here!',
        'schema_types' => ['WebPage'],
    ],
    '/dublin-ca-turf-cleaning' => [
        'slug' => 'dublin-ca-turf-cleaning',
        'template' => 'page',
        'title' => 'Dublin-CA-turf-cleaning | Clean Green Turf',
        'description' => 'Boost your Dublin, CA artificial turf with Clean Green Turf’s efficient, eco-friendly cleaning services. Enjoy a spotless, safe, and stunning outdoor space—optimized for beauty and sustainability!',
        'schema_types' => ['WebPage'],
    ],
    '/fremont-ca-turf-cleaning' => [
        'slug' => 'fremont-ca-turf-cleaning',
        'template' => 'page',
        'title' => 'Fremont-CA-turf-cleaning | Clean Green Turf',
        'description' => 'Revitalize your Fremont, CA artificial turf with Clean Green Turf’s expert, eco-friendly cleaning. Enhance longevity, hygiene, and curb appeal with our thorough, safe, and sustainable solutions!',
        'schema_types' => ['WebPage'],
    ],
    '/frisco-tx-turf-cleaning' => [
        'slug' => 'frisco-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'Artificial Turf Cleaning in Frisco, TX | Clean Green Turf',
        'description' => 'Professional artificial turf cleaning in Frisco, TX. We fully extract pet odors, deep clean, and restore your turf. Pet-safe, family-safe, and built for DFW summers. Free quote: (469) 796-0034.',
        'schema_types' => ['WebPage'],
    ],
    '/how-to-clean-indoor-turf' => [
        'slug' => 'how-to-clean-indoor-turf',
        'template' => 'page',
        'title' => 'How to Clean Indoor Turf | Clean Green Turf',
        'description' => 'Tips and tricks for how to clean indoor sports field artificial turf. Why you should hire a professional.',
        'schema_types' => ['Article'],
    ],
    '/livermore-ca-turf-cleaning' => [
        'slug' => 'livermore-ca-turf-cleaning',
        'template' => 'page',
        'title' => 'Livermore-CA-turf-cleaning | Clean Green Turf',
        'description' => 'Elevate your Livermore, CA artificial turf with Clean Green Turf’s fast, eco-friendly cleaning services. Enjoy pristine, durable, and green lawns with our expert, environmentally conscious care!',
        'schema_types' => ['WebPage'],
    ],
    '/mckinney-tx-turf-cleaning' => [
        'slug' => 'mckinney-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'Artificial Turf Cleaning in McKinney, TX | Clean Green Turf',
        'description' => 'Turf cleaning in McKinney, TX trusted by homeowners across Craig Ranch, Stonebridge Ranch, and Eldorado. Full pet odor extraction, not masking. Free quote: (469) 796-0034.',
        'schema_types' => ['WebPage'],
    ],
    '/plano-tx-turf-cleaning' => [
        'slug' => 'plano-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'Plano-TX-turf-cleaning | Clean Green Turf',
        'description' => 'Keep your Plano, TX artificial turf vibrant and durable with Clean Green Turf’s efficient, eco-friendly cleaning. We eliminate dirt, debris, and bacteria, delivering pristine results without compromise!',
        'schema_types' => ['WebPage'],
    ],
    '/prosper-tx-turf-cleaning' => [
        'slug' => 'prosper-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'Prosper professional turf cleaning | Clean Green Turf',
        'description' => 'Transform your Prosper, TX artificial turf with Clean Green Turf’s top-notch, eco-friendly cleaning. Efficient and thorough, we banish dirt, bacteria, and odors—hassle-free perfection awaits!',
        'schema_types' => ['WebPage'],
    ],
    '/richardson-tx-turf-cleaning' => [
        'slug' => 'richardson-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'Richardson-TX-turf-cleaning | Clean Green Turf',
        'description' => 'Refresh your Richardson, TX artificial turf with Clean Green Turf’s fast, eco-friendly cleaning. Affordable and thorough, we zap odors and boost longevity for a stunning, green lawn!',
        'schema_types' => ['WebPage'],
    ],
    '/rockwall-tx-turf-cleaning' => [
        'slug' => 'rockwall-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'Rockwall TX Turf Cleaning — Fresh, Clean Turf for Lakeside Living | Clean Green Turf',
        'description' => 'Artificial turf cleaning in Rockwall, TX serving Chandler Creek, Heath, and lakefront communities. Full pet odor extraction. Pet-safe, family-safe. Free quote: (469) 796-0034.',
        'schema_types' => ['WebPage'],
    ],
    '/reschedule' => [
        'slug' => 'reschedule',
        'template' => 'page',
        'title' => 'Reschedule Your Estimate | Clean Green Turf',
        'description' => 'Reschedule or cancel your turf installation estimate appointment.',
        'schema_types' => [],
        'robots' => 'noindex, nofollow',
    ],
    '/schedule-turf-installation-estimate' => [
        'slug' => 'schedule-turf-installation-estimate',
        'template' => 'page',
        'title' => 'Schedule a Free Turf Installation Estimate | Clean Green Turf',
        'description' => 'Pick a day and time for a free in-person artificial turf installation estimate in the DFW metroplex. Fast confirmation, text reminder the day before.',
        'schema_types' => ['WebPage'],
    ],
    '/texas-service-areas' => [
        'slug' => 'texas-service-areas',
        'template' => 'page',
        'title' => 'DFW Turf Cleaning Service Areas — Every City We Serve | Clean Green Turf',
        'description' => 'Clean Green Turf serves the entire DFW metroplex. Frisco, McKinney, Prosper, Allen, Plano, Dallas, Rockwall, Richardson, Celina, Addison, and more. Free quote: (469) 796-0034.',
        'schema_types' => ['WebPage'],
    ],
    '/the-colony-tx-turf-cleaning' => [
        'slug' => 'the-colony-tx-turf-cleaning',
        'template' => 'page',
        'title' => 'The Colony-TX-turf-cleaning | Clean Green Turf',
        'description' => 'Discover rapid, eco-friendly artificial turf cleaning with Clean Green Turf in The Colony, TX. Our sustainable, thorough methods keep your turf pristine, vibrant, and bacteria-free—cleanliness meets green living!',
        'schema_types' => ['WebPage'],
    ],
    '/turf-installation' => [
        'slug' => 'turf-installation',
        'template' => 'page',
        'title' => 'Artificial Turf Installation in DFW, TX | Clean Green Turf',
        'description' => 'Full artificial turf installation for backyards, front yards, and pet runs across the DFW Metroplex — proper base prep, drainage, and seaming. Schedule a free in-person estimate.',
        'schema_types' => ['WebPage'],
    ],
    '/turf-repair' => [
        'slug' => 'turf-repair',
        'template' => 'page',
        'title' => 'Artificial Turf Repair in DFW, TX | Clean Green Turf',
        'description' => 'Artificial turf repair for loose seams, sunken patches, sun-damaged fibers, and pet damage across the DFW Metroplex. Free assessment and quote.',
        'schema_types' => ['WebPage'],
    ],
    '/turf-sports-field-maintenance' => [
        'slug' => 'turf-sports-field-maintenance',
        'template' => 'page',
        'title' => 'Artificial Turf Field Testing & Performance Analysis | Clean Green Turf',
        'description' => 'How Clean Green Turf tests and maintains artificial sports fields for drainage, infill depth, and player-surface performance.',
        'schema_types' => ['WebPage'],
    ],

    '/blog-post' => [
        'slug' => 'blog-post',
        'template' => 'article',
        'title' => 'How Often Should You Clean Artificial Turf? A Seasonal Maintenance Schedule | Clean Green Turf',
        'description' => 'A season-by-season guide to how often artificial turf actually needs professional cleaning, based on pets, climate, and usage.',
        'schema_types' => ['Article'],
        'date_published' => '2026-09-08',
    ],
    '/blog-post1' => [
        'slug' => 'blog-post1',
        'template' => 'article',
        'title' => 'Pet Turf Odor: Why Rinsing Isn\'t Enough (and What Actually Works) | Clean Green Turf',
        'description' => 'Why hosing down artificial turf doesn\'t fix pet odor, what\'s happening below the surface, and what actually eliminates it for good.',
        'schema_types' => ['Article'],
        'date_published' => '2026-09-08',
    ],
    '/blog-post2' => [
        'slug' => 'blog-post2',
        'template' => 'article',
        'title' => 'Artificial Turf Infill 101: What It Is and Why It Needs Replenishing | Clean Green Turf',
        'description' => 'What artificial turf infill actually does, why it depletes over time, and the signs your yard needs it topped off.',
        'schema_types' => ['Article'],
        'date_published' => '2026-09-08',
    ],
    '/blog-post3' => [
        'slug' => 'blog-post3',
        'template' => 'article',
        'title' => 'DIY vs. Professional Artificial Turf Cleaning: What You Can (and Can\'t) Do Yourself | Clean Green Turf',
        'description' => 'A practical breakdown of which turf maintenance tasks are safe to DIY and which ones need professional equipment and treatment.',
        'schema_types' => ['Article'],
        'date_published' => '2026-09-08',
    ],
    '/blog-post4' => [
        'slug' => 'blog-post4',
        'template' => 'article',
        'title' => 'How DFW Weather Extremes Affect Artificial Turf | Clean Green Turf',
        'description' => 'How North Texas heat, hail, freezes, and drought each affect artificial turf differently, and how to adjust your cleaning schedule for DFW weather.',
        'schema_types' => ['Article'],
        'date_published' => '2026-09-08',
    ],
];
